chore: update create-release action to 1.10
Hopefully the following error will no longer occur when invoking this
action:

Error: Parameter token or opts.auth is required

Note that this error occurred even when a token was supplied.